languageCode = "en"
languageName = "English"
weight = 1
title = "9upper"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
   logo = "img/Tux/Tux-cute.png"
   secondaryLogo = "img/secondary-logo.png"
   description = "Welcome to my blog."
   copyright = "Copyright © 2020-2023 - Arcsly"

 [author]
   name = "9upper"
   image = "img/Tux/Tux-cute.png"
   headline = "I use linux btw. Penguin so cute."
   bio = "eat, sleep and code."
   links = [
     { email = "mailto:hello@your_domain.com" },
     { link = "https://ummit.dev" },
     { discord = "https://discord.gg/invitecode" },
     { gitlab = "https://gitlab.com/username" },
     { mastodon = "https://mastodon.instance/@username" }
   ]