languageCode = "en"
languageName = "English"
weight = 1
title = "UmmIt"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/推しの子/cutecutecute.jpg"
  description = "Welcome to my blog."
  copyright = """Copyright © 2020-2025 - UmmIt<br/>
All articles are under CC BY-SA 4.0 License
"""

[params.author]
   name = "UmmIt"
   image = "img/推しの子/cutecutecute.jpg"
   headline = "GNU/Linux Enthusiast :)"
   bio = "Loves to write about technology, and cybersecurity related topics :)"
   links = [
     { ko-fi = "https://ko-fi.com/UmmIt"},
     { github = "https://github.com/UmmItC"},
     { codeberg = "https://codeberg.org/UmmIt"},
     { email = "mailto:blog@ummit.dev" },
     { pgpkey = "https://gitlab.com/UmmIt.gpg"}
   ]
