default:
  image: "${CI_TEMPLATE_REGISTRY_HOST}/pages/hugo:0.121.1"

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GL_PAGES_URL: gl-blog.ummit.dev
  
test:
  script:
    - hugo -v
  rules:
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH

pages:
  script:
    - hugo $GL_PAGES_URL
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  environment: production
