# hugo.yml
#
# Takes a repository with Hugo source, generates the static site and
# pushes the result to Codeberg pages
#
# Needs a codeberg access token (codeberg_token) as a secret in Woodpecker config
# Make sure the codeberg_token has "Repository and Organization Access" -> "package" -> "Read and Write"
# Also uses another secret (mail) with email address for git config
#
# .domains file in the repository is copied to the output branch so custom domains work
#
# The HUGO_OUTPUT variable must be set to the build output folder configured in Hugo
#

# Exclude page pipeline to be run on "pages" branch
when:
  branch:
    exclude: pages
  event: [push, pull_request]

# Recursive cloning is used to fully clone the themes given as Git submodules
clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      recursive: true

steps:
  # Build hugo static files
  build:
    image: hugomods/hugo:exts
    commands:
      - hugo --minify -b "https://cb-blog.ummit.dev"
    when:
      event: [pull_request, push]

  publish:
    image: bitnami/git
    environment:
      HUGO_OUTPUT: public
      # secrets must be set in Woodpecker configuration
      MAIL:
        from_secret: mail
      CODEBERG_TOKEN:
        from_secret: codeberg_token
    commands:
      # Git configuration
      - git config --global user.email $MAIL
      - git config --global user.name "Woodpecker CI"

      - cd ..
      - git clone -b pages https://$CODEBERG_TOKEN@codeberg.org/UmmIt/pages.git pages
      - echo "cb-blog.ummit.dev" > .domains

      # test
      - cat .domains
      - ls
      - pwd

      # Copy build step output to repository folder
      - cp -ar Blog/$HUGO_OUTPUT/. pages/

      # Copy custom domains file
      - cp -v .domains pages/
      
      # Commit and push all static files with pipeline started timestamp
      - cd pages
      - git add .
      - git commit -m "Woodpecker CI Commit SHA ${CI_COMMIT_SHA}"
      - git push origin pages
    when:
      event: push
