name: Deploy Hugo Blog
on:
  push:
    branches:
      - 'codeberg_action'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.121.2
    steps:
      - run: ping -c 5 codeberg.org
      - run: curl https://codeberg.org
