name: Deploy Hugo Blog
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.121.1
    steps:
      - name: Install Hugo CLI
        run: |
          echo "Installing Hugo CLI..."
          wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_linux-amd64.deb \
          && dpkg -i hugo_${HUGO_VERSION}_linux-amd64.deb && hugo version && echo "Install Hugo CLI Done"

