name: Demo
run-name: ${{ github.actor }} is testing
on: [push]
jobs:
  Explore-CI:
    runs-on: alpine
    steps:
      - run: apk update -U && apk add git hugo
        shell: sh
      - uses: actions/checkout@v3
        with:
          submodules: true
