name: Hugo

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@va3
      - run: |
          date > generated.txt
          git config user.name UmmIt-Bot
          git config user.email bot@ummit.dev
          git add .
          git commit -m "generated"
          git push
