name: Deploy Hugo Blog
on:
  push:
    branches:
      - 'codeberg_action'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.121.1
    steps:
      - run: wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_linux-amd64.deb
      - run: dpkg -i hugo_${HUGO_VERSION}_linux-amd64.deb
      - run: pwd && ls
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: hugo && echo "done"
      #- run: hugo && echo "Build done."
