name: Demo
on: [push]

jobs:
  Explore-CI:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
      - uses: klakegg/hugo
        with:
          go-version: '^1.13.1'
      - run: go version
      - run: hugo version
