name: Demo
run-name: ${{ github.actor }} is testing
on: [push]
jobs:
  Explore-CI:
    runs-on: ubuntu-latest
    steps:
      - run: apt install hugo -y 
      - run: echo "Testing :D"
      - run: hugo
