name: Deploy Hugo Blog
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.121.1
    steps:
      - name: Install Hugo CLI
      - run: apt update && apt upgrade
      - run: |
          wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_linux-amd64.deb \
          && dpkg -i hugo_${HUGO_VERSION}_linux-amd64.deb && hugo && echo "Build done"
