name: Push
on: [push]

jobs:
  push:
    runs-on: ubuntu-lastest
    steps:
      - run: apt update && apt install hugo
        shell: sh
      - uses: actions/checkout@v3
        with:
          submodules: true
      - run: hugo
