name: Push
on: [push]

jobs:
  push:
    runs-on: debian
    steps:
      - run: apt update -y && apt upgrade -y && apt install hugo
        shell: sh
      - uses: actions/checkout@v3
      - run: hugo server --loglevel debug

