# hugo.yml
#
# Takes a repository with Hugo source, generates the static site and
# pushes the result to Codeberg pages
#
# Needs a codeberg access token (codeberg_token) as a secret in Woodpecker config
# Make sure the codeberg_token has "Repository and Organization Access" -> "package" -> "Read and Write"
# Also uses another secret (mail) with email address for git config
#
# .domains file in the repository is copied to the output branch so custom domains work
#
# The HUGO_OUTPUT variable must be set to the build output folder configured in Hugo
#

# Exclude page pipeline to be run on "pages" branch
when:
  branch:
    exclude: pages
  event: [push, pull_request]

# Recursive cloning is used to fully clone the themes given as Git submodules
clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      recursive: true

steps:
  # Build hugo static files
  build:
    image: hugomods/hugo:exts
    commands:
      # Build the static site and minify it and set the base URL for the domain
      - hugo --minify -b "https://cb-blog.ummit.dev"
    when:
      event: [pull_request, push]

  publish:
    image: bitnami/git
    environment:
      HUGO_OUTPUT: public
      # secrets must be set in Woodpecker configuration
      MAIL:
        from_secret: mail
      CODEBERG_TOKEN:
        from_secret: codeberg_token
    commands:

      # Git configuration
      - git config --global user.email $MAIL
      - git config --global user.name "Woodpecker CI"

      # There would be already after the hugo build
      # Change the directory to the root of the repository
      - cd ..

      # Under the root path, clone the pages branch
      - git clone -b pages https://$CODEBERG_TOKEN@codeberg.org/UmmIt/pages.git pages

      # Copy the new hugo static files to the pages branch
      - cp -ar Blog/$HUGO_OUTPUT/. pages/
      # Copy the .domains file to the pages branch (from Blog repository)
      - cp -v Blog/.domains pages/

      - git remote -v
      - git config --list
           
      # Lastly, commit to repository pages branch and push changes
      - cd pages
      - git add .
      - git commit -m "[Woodpecker CI] Update static site content - Commit SHA ${CI_COMMIT_SHA}"
      - git push origin pages
    when:
      event: push
